version: '3.1'
services:
  mongo: 
    image: mongo 
    ports:  
      - '27017:27017'
    command: --serviceExecutor adaptive
    volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro